import { BusinessInfo } from "./types";

export const SERVICE_SUSPENDED = true;

export const PLACEHOLDER_EXAMPLES: BusinessInfo[] = [
  {
    companyName: "Calors Automóveis",
    phone: "(21) 99997-3749",
    email: "contato@calorsauto.com.br",
    instagram: "@calors.auto",
    facebook: "/calorsautomoveis",
    website: "www.calorsauto.com.br",
    addressStreet: "Rua Silenciosa",
    addressNumber: "278",
    addressNeighborhood: "São José",
    addressCity: "Rio de Janeiro",
    details: "Oficina mecânica completa. Faço lanternagem, pintura, rebaixamento, consertos de motor e troca de óleo. Faço tudo em carros nacionais e importados.",
    logo: ""
  },
  {
    companyName: "Dra. Ana Estética",
    phone: "(11) 98888-5555",
    email: "agendamento@draana.com.br",
    instagram: "@dra.anaestetica",
    facebook: "/draanaestetica",
    website: "www.draanaestetica.com.br",
    addressStreet: "Av. Paulista",
    addressNumber: "1000",
    addressNeighborhood: "Bela Vista",
    addressCity: "São Paulo",
    details: "Harmonização facial, botox, preenchimento labial e limpeza de pele. Clínica de alto padrão com equipamentos modernos.",
    logo: ""
  },
  {
    companyName: "Pizzaria do Chef",
    phone: "(31) 97777-1234",
    email: "pedidos@pizzariadochef.com.br",
    instagram: "@pizzariadochef_bh",
    facebook: "/pizzariadochef",
    website: "www.pizzariadochef.com.br",
    addressStreet: "Rua do Ouro",
    addressNumber: "50",
    addressNeighborhood: "Serra",
    addressCity: "Belo Horizonte",
    details: "Pizza artesanal em forno a lenha. Promoção de terça-feira: compre uma gigante e ganhe um refrigerante. Entregamos em toda a região.",
    logo: ""
  },
  {
    companyName: "Escritório Silva Advocacia",
    phone: "(41) 3333-9999",
    email: "contato@silvaadv.com.br",
    instagram: "@silva.advocacia",
    facebook: "/silvaadvocacia",
    website: "www.silvaadv.com.br",
    addressStreet: "Rua das Flores",
    addressNumber: "12",
    addressNeighborhood: "Centro",
    addressCity: "Curitiba",
    details: "Especialista em causas trabalhistas e previdenciárias. Aposentadoria, auxílio doença e revisão de benefícios. Atendimento humanizado.",
    logo: ""
  },
  {
    companyName: "Academia FitPower",
    phone: "(85) 99123-4567",
    email: "matricula@fitpower.com.br",
    instagram: "@fitpower.academia",
    facebook: "/academiafitpower",
    website: "www.fitpower.com.br",
    addressStreet: "Av. Beira Mar",
    addressNumber: "500",
    addressNeighborhood: "Meireles",
    addressCity: "Fortaleza",
    details: "Academia completa com musculação, crossfit, spinning e pilates. Professores qualificados. Promoção: primeira semana grátis!",
    logo: ""
  },
  {
    companyName: "Salão Beleza Pura",
    phone: "(71) 98765-4321",
    email: "agende@belezapura.com.br",
    instagram: "@salaobelezapural",
    facebook: "/salaobelezapural",
    website: "www.belezapura.com.br",
    addressStreet: "Rua Chile",
    addressNumber: "88",
    addressNeighborhood: "Comércio",
    addressCity: "Salvador",
    details: "Corte, coloração, escova progressiva, manicure e pedicure. Atendemos noivas e festas. Produtos de primeira linha.",
    logo: ""
  },
  {
    companyName: "Hamburgueria Artesanal",
    phone: "(48) 99888-7777",
    email: "delivery@burguerartesanal.com.br",
    instagram: "@hamburgueria.artesanal",
    facebook: "/hamburgueriaartesanal",
    website: "www.burguerartesanal.com.br",
    addressStreet: "Rua Felipe Schmidt",
    addressNumber: "200",
    addressNeighborhood: "Centro",
    addressCity: "Florianópolis",
    details: "Hambúrguer artesanal com carne angus, pão brioche e molhos especiais. Delivery rápido. Combo promocional de segunda a quinta.",
    logo: ""
  },
  {
    companyName: "Pet Shop Amigo Fiel",
    phone: "(61) 98111-2222",
    email: "contato@amigofiel.com.br",
    instagram: "@petshopamigofiel",
    facebook: "/petshopamigofiel",
    website: "www.amigofiel.com.br",
    addressStreet: "Quadra 5",
    addressNumber: "Lote 10",
    addressNeighborhood: "Asa Sul",
    addressCity: "Brasília",
    details: "Banho e tosa, veterinário, ração premium e acessórios. Cuidamos do seu pet com carinho. Agendamento online disponível.",
    logo: ""
  },
  {
    companyName: "Consultoria Mendes",
    phone: "(19) 97654-3210",
    email: "contato@mendesconsultoria.com.br",
    instagram: "@mendes.consultoria",
    facebook: "/mendesconsultoria",
    website: "www.mendesconsultoria.com.br",
    addressStreet: "Av. Norte Sul",
    addressNumber: "1500",
    addressNeighborhood: "Cambuí",
    addressCity: "Campinas",
    details: "Consultoria empresarial, planejamento estratégico e gestão financeira. Ajudamos sua empresa a crescer de forma sustentável.",
    logo: ""
  },
  {
    companyName: "Padaria Pão Quente",
    phone: "(27) 99333-4444",
    email: "encomendas@paoquente.com.br",
    instagram: "@padariapaoquente",
    facebook: "/padariapaoquente",
    website: "www.paoquente.com.br",
    addressStreet: "Rua Sete",
    addressNumber: "45",
    addressNeighborhood: "Praia do Canto",
    addressCity: "Vitória",
    details: "Pães artesanais, doces, salgados e café da manhã completo. Aberto todos os dias das 6h às 22h. Encomendas para festas.",
    logo: ""
  },
  {
    companyName: "Loja de Roupas Fashion",
    phone: "(51) 98222-3333",
    email: "vendas@fashionstore.com.br",
    instagram: "@fashionstore.poa",
    facebook: "/fashionstorepoa",
    website: "www.fashionstore.com.br",
    addressStreet: "Rua dos Andradas",
    addressNumber: "1234",
    addressNeighborhood: "Centro Histórico",
    addressCity: "Porto Alegre",
    details: "Moda feminina e masculina. Lançamentos toda semana. Parcelamos em até 10x sem juros. Frete grátis acima de R$ 200.",
    logo: ""
  },
  {
    companyName: "Clínica Odontológica Sorriso",
    phone: "(62) 99444-5555",
    email: "agende@clinicasorriso.com.br",
    instagram: "@clinicasorriso.go",
    facebook: "/clinicasorrisogo",
    website: "www.clinicasorriso.com.br",
    addressStreet: "Av. T-9",
    addressNumber: "800",
    addressNeighborhood: "Setor Bueno",
    addressCity: "Goiânia",
    details: "Implantes, aparelhos ortodônticos, clareamento e limpeza. Primeira consulta grátis. Parcelamento facilitado.",
    logo: ""
  },
  {
    companyName: "Açaí do Mano",
    phone: "(91) 98777-6666",
    email: "pedidos@acaidomano.com.br",
    instagram: "@acaidomano",
    facebook: "/acaidomano",
    website: "www.acaidomano.com.br",
    addressStreet: "Travessa Quintino",
    addressNumber: "66",
    addressNeighborhood: "Cremação",
    addressCity: "Belém",
    details: "Açaí puro, cremoso e gelado. Mais de 30 acompanhamentos. Delivery rápido. Promoção: açaí 500ml + 3 acompanhamentos por R$ 15.",
    logo: ""
  },
  {
    companyName: "Auto Escola Direção Segura",
    phone: "(82) 99555-7777",
    email: "matricula@direcaosegura.com.br",
    instagram: "@direcaosegura.al",
    facebook: "/direcaoseguraal",
    website: "www.direcaosegura.com.br",
    addressStreet: "Rua do Comércio",
    addressNumber: "300",
    addressNeighborhood: "Farol",
    addressCity: "Maceió",
    details: "CNH categoria A e B. Instrutores experientes, carros novos e aulas práticas no trânsito real. Aprovação garantida.",
    logo: ""
  },
  {
    companyName: "Lavanderia Express",
    phone: "(84) 98666-8888",
    email: "contato@lavanderiaexpress.com.br",
    instagram: "@lavanderiaexpress.rn",
    facebook: "/lavanderiaexpressrn",
    website: "www.lavanderiaexpress.com.br",
    addressStreet: "Av. Senador Salgado",
    addressNumber: "1000",
    addressNeighborhood: "Lagoa Nova",
    addressCity: "Natal",
    details: "Lavagem a seco, passadoria e higienização de estofados. Serviço rápido e de qualidade. Pegamos e entregamos em casa.",
    logo: ""
  },
  {
    companyName: "Floricultura Jardim Encantado",
    phone: "(92) 99777-9999",
    email: "pedidos@jardimencantado.com.br",
    instagram: "@jardimencantado.am",
    facebook: "/jardimencantadoam",
    website: "www.jardimencantado.com.br",
    addressStreet: "Av. Constantino Nery",
    addressNumber: "2500",
    addressNeighborhood: "Chapada",
    addressCity: "Manaus",
    details: "Arranjos florais, buquês, cestas de café da manhã e plantas ornamentais. Entregamos em toda a cidade. Encomendas para eventos.",
    logo: ""
  },
  {
    companyName: "Assistência Técnica TechFix",
    phone: "(83) 98888-0000",
    email: "suporte@techfix.com.br",
    instagram: "@techfix.jp",
    facebook: "/techfixjp",
    website: "www.techfix.com.br",
    addressStreet: "Rua Maciel Pinheiro",
    addressNumber: "150",
    addressNeighborhood: "Centro",
    addressCity: "João Pessoa",
    details: "Conserto de celulares, notebooks e tablets. Troca de tela, bateria e reparo de placa. Orçamento grátis. Garantia de 90 dias.",
    logo: ""
  },
  {
    companyName: "Escola de Idiomas Fluent",
    phone: "(86) 99999-1111",
    email: "matricula@fluentidiomas.com.br",
    instagram: "@fluent.idiomas",
    facebook: "/fluentidiomas",
    website: "www.fluentidiomas.com.br",
    addressStreet: "Av. Frei Serafim",
    addressNumber: "2000",
    addressNeighborhood: "Centro",
    addressCity: "Teresina",
    details: "Inglês, espanhol e francês. Aulas presenciais e online. Professores nativos. Método exclusivo de conversação. Matrícula aberta!",
    logo: ""
  }
];