
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'backend', 'server.cjs');
let content = fs.readFileSync(filePath, 'utf8');

const updatedLogic = `    // === GENERATION LOGIC (Corrected & Validated v4) ===
    const generateImage = async (directorPrompt) => {
      let professionalPrompt = \`Professional commercial flyer for \${promptInfo.companyName}.\`;
      
      try {
        // 1. IMPROVE PROMPT WITH GEMINI
        const result = await model.generateContent(directorPrompt);
        professionalPrompt = result.response.text().trim().replace(/\`\`\`/g, '');
        console.log('🤖 Director Smart Prompt:', professionalPrompt);

        // 2. ROBUST DATA INJECTION
        const clientData = [];
        if (promptInfo.companyName) clientData.push(\`Nome do Negócio: \${promptInfo.companyName}\`);
        
        const phoneFn = promptInfo.phone || promptInfo.whatsapp;
        if (phoneFn) clientData.push(\`WhatsApp/Tel: \${phoneFn}\`);
        if (promptInfo.instagram) clientData.push(\`Instagram: \${promptInfo.instagram}\`);

        if (promptInfo.addressStreet) {
            const addrParts = [promptInfo.addressStreet, promptInfo.addressNumber, promptInfo.addressNeighborhood, promptInfo.addressCity].filter(Boolean);
            clientData.push(\`Endereço: \${addrParts.join(', ')}\`);
        } else if (promptInfo.rua) {
            clientData.push(\`Endereço: \${promptInfo.rua}\`);
        }
        
        if (promptInfo.site) clientData.push(\`Site: \${promptInfo.site}\`);
        if (promptInfo.details) clientData.push(\`Detalhes: \${promptInfo.details}\`);

        if (clientData.length > 0) {
          const robustBlock = \`\\n═══════════════════════════════════════════════════════════════\\n⚠️ DADOS REAIS DO CLIENTE - COPIE EXATAMENTE COMO ESTÁ ESCRITO ⚠️\\n═══════════════════════════════════════════════════════════════\\n\\n\${clientData.join('\\n')}\\n\\n═══════════════════════════════════════════════════════════════\\n📋 INSTRUÇÕES OBRIGATÓRIAS:\\n═══════════════════════════════════════════════════════════════\\n1. COPIE cada texto EXATAMENTE como aparece acima, letra por letra\\n2. NÃO traduza - mantenha em português brasileiro\\n3. NÃO mude, adicione ou remova NENHUM caractere\\n4. NÃO invente dados - use SOMENTE os dados listados acima\\n5. Se um campo não está listado acima, NÃO inclua no cartão\\n6. IMPORTANTE: Os dados acima são os ÚNICOS dados verdadeiros. NÃO use nenhum outro texto.\\n\`;
          professionalPrompt += robustBlock;
          console.log('💉 Data Injected (Robust V2):', robustBlock);
        }

        // 3. CALL IMAGEN API
        const response = await axios.post(
          \`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=\${GEMINI_API_KEY}\`,
          {
            instances: [{ prompt: professionalPrompt }],
            parameters: { sampleCount: 1, aspectRatio: "3:4" }
          },
          { headers: { 'Content-Type': 'application/json' }, timeout: 90000 }
        );

        const b64 = response.data?.predictions?.[0]?.bytesBase64Encoded;
        if (!b64) throw new Error('No image generated by API');
        
        return { b64, professionalPrompt };

      } catch (e) {
        if (e.code === 'ECONNABORTED') throw new Error('Timeout: A IA demorou muito para responder.');
        console.error('Artist Error:', e.response?.data || e.message);
        throw new Error(e.response?.data?.error?.message || e.message || 'Erro ao gerar imagem');
      }
    };

    // CALL GENERATION (New Logic)
    const { b64: imageBase64, professionalPrompt: finalPrompt } = await generateImage(directorPrompt);
    let criticVerdict = 'SKIPPED';
`;

// Find markers
const startMarker = "Professional commercial flyer for ${promptInfo.companyName}.`;";
// We use a robust marker. The 'let professionalPrompt' line was at 535ish.
// But we should look for the START of the helper function?
// Or better: Search for "const generateImage = async (directorPrompt) => {" which we inserted?
// Or look for "const directorPrompt =" which is BEFORE our block (line 496).
// Let's use "const directorPrompt =" as anchor and "let criticVerdict =" (which we want to replace/reinsert) or "// THE CRITIC".

const startAnchor = 'let professionalPrompt = `Professional commercial flyer for ${promptInfo.companyName}.`;';
const endAnchor = '// THE CRITIC';

// Note: startAnchor might have been deleted/replaced in previous attempts.
// Safe fallback: Look for "const directorPrompt =" and replace UNTIL "// THE CRITIC".
// But "directorPrompt" definition is way above.

// Let's try to find "const generateImage" (the one we added) or what is left of it.
const startIndex = content.indexOf('const generateImage = async (directorPrompt) => {');
const endIndex = content.indexOf('// THE CRITIC');

if (startIndex === -1 || endIndex === -1) {
    console.error('Markers not found! Start:', startIndex, 'End:', endIndex);
    // Fallback: search for "let professionalPrompt"
    const fallbackStart = content.indexOf('let professionalPrompt = `Professional');
    if (fallbackStart === -1) {
        console.error('Fallback marker not found explicitly. Dumping snippet around 530:');
        console.log(content.substring(20000, 21000));
        process.exit(1);
    }
}

// We want to replace from "const generateImage..." (or before it if we have the "=== GENERATION LOGIC" comment)
// Let's search for "=== GENERATION LOGIC"
const commentStart = content.indexOf('// === GENERATION LOGIC');
const cleanStart = commentStart !== -1 ? commentStart : startIndex;

// Replace content
const newContent = content.substring(0, cleanStart) + updatedLogic + '\n\n' + content.substring(endIndex);

fs.writeFileSync(filePath, newContent);
console.log('Successfully brute-forced server.cjs');
